on:
  push:
    branches:
      - delete-resources

jobs:
  delete-resources:
    runs-on: ubuntu-latest
    steps:
    - name: Delete Azure Container Registry Image
      run: |
        az acr repository delete --name acracks33 --image myimage:${{ github.sha }} --yes

    - name: Delete Kubernetes Resources
      run: |
        kubectl delete -f kube-manifests/01-Deployment-and-LoadBalancer-Service.yml
