name: Delete

on:
  workflow_dispatch: # Esto hace que el action se lance de forma manual

env:
  REGISTRY_NAME: acracks33
  CLUSTER_NAME: aks-pub-priv
  CLUSTER_RESOURCE_GROUP: agic-pub-priv-rg
  NAMESPACE: default

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
    - name: Delete Image
      run: |
        # Elimina la imagen del registro de contenedor
        az acr repository delete --name acracks33 --image myimage:${{ github.sha }} --yes
    - name: Delete Deployment
      run: |
        # Elimina el deployment utilizando los archivos de manifiesto
        kubectl delete -f kube-manifests/01-Deployment-and-LoadBalancer-Service.yml
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
