name: Delete

on:
  workflow_dispatch:

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
    - name: Delete Image
      run: |
        # Eliminar la imagen del registro de contenedores
        az acr repository delete --name acracks33 --image myimage:${{ github.sha }} --yes
      env:
        AZURE_SERVICE_PRINCIPAL_APP_ID: ${{ secrets.AZURE_SP_APP_ID }}
        AZURE_SERVICE_PRINCIPAL_PASSWORD: ${{ secrets.AZURE_SP_PASSWORD }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    - name: Delete Deployment
      run: |
        # Eliminar el despliegue de Kubernetes
        az login --service-principal -u ${{ secrets.AZURE_SP_APP_ID }} -p ${{ secrets.AZURE_SP_PASSWORD }} --tenant ${{ secrets.AZURE_TENANT_ID }}
        az aks get-credentials --resource-group agic-pub-priv-rg --name aks-pub-priv --overwrite-existing
        kubectl delete -f kube-manifests/01-Deployment-and-LoadBalancer-Service.yml
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
