name: Delete Deployment

on:
  workflow_dispatch:

env:
  CLUSTER_NAME: aks-pub-priv
  CLUSTER_RESOURCE_GROUP: agic-pub-priv-rg
  NAMESPACE: default

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
    - name: Set up kubectl
      uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ env.CLUSTER_NAME }}
        resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}

    - name: Delete Deployment
      run: |
        kubectl delete -f kube-manifests/01-Deployment-and-LoadBalancer-Service.yml
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
